[package]
name    = "nova-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow    = { workspace = true }
thiserror = { workspace = true }
serde     = { workspace = true }
serde_json = { workspace = true }
ropey     = { workspace = true }
toml      = { workspace = true }
dirs      = { workspace = true }
sha2      = { workspace = true }
